### ISSUE TITLE
composer.json cleanup

### ISSUE THREAD

**Issue by elazar** [trvshrmn/slim-skeleton#3]
Dependencies used for development only (as opposed to production), such as `tracy/tracy` and `friendsofphp/php-cs-fixer`, should be in [`require-dev`](https://getcomposer.org/doc/04-schema.md#require-dev) rather than [`require`](https://getcomposer.org/doc/04-schema.md#require).

Ideally, the dependencies listed within `require` and `require-dev` should be alphabetized so they're easy to visually scan.

**Comment by trvshrmn** [comment]
I didn't know anything about `require-dev`. I read some and see that I can enter `composer install --no-dev` and it will remove the things not needed for production. Is this the main purpose for `require-dev`?

**Comment by elazar** [comment]
Yes.
